development:
  sessions:
    default:
      database: note_mod_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: note_mod_test
      hosts:
        - localhost:27017